<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_gajipokok extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Tbl_gajipokok_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','tbl_gajipokok/tbl_gajipokok_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tbl_gajipokok_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tbl_gajipokok_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_jabatan' => $row->id_jabatan,
		'jabatan' => $row->jabatan,
		'gaji_pokok' => $row->gaji_pokok,
	    );
            $this->template->load('template','tbl_gajipokok/tbl_gajipokok_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbl_gajipokok'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('tbl_gajipokok/create_action'),
	    'id_jabatan' => set_value('id_jabatan'),
	    'jabatan' => set_value('jabatan'),
	    'gaji_pokok' => set_value('gaji_pokok'),
	);
        $this->template->load('template','tbl_gajipokok/tbl_gajipokok_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'jabatan' => $this->input->post('jabatan',TRUE),
		'gaji_pokok' => $this->input->post('gaji_pokok',TRUE),
	    );

            $this->Tbl_gajipokok_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('tbl_gajipokok'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbl_gajipokok_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('tbl_gajipokok/update_action'),
		'id_jabatan' => set_value('id_jabatan', $row->id_jabatan),
		'jabatan' => set_value('jabatan', $row->jabatan),
		'gaji_pokok' => set_value('gaji_pokok', $row->gaji_pokok),
	    );
            $this->template->load('template','tbl_gajipokok/tbl_gajipokok_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbl_gajipokok'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_jabatan', TRUE));
        } else {
            $data = array(
		'jabatan' => $this->input->post('jabatan',TRUE),
		'gaji_pokok' => $this->input->post('gaji_pokok',TRUE),
	    );

            $this->Tbl_gajipokok_model->update($this->input->post('id_jabatan', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('tbl_gajipokok'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbl_gajipokok_model->get_by_id($id);

        if ($row) {
            $this->Tbl_gajipokok_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('tbl_gajipokok'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tbl_gajipokok'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('jabatan', 'jabatan', 'trim|required');
	$this->form_validation->set_rules('gaji_pokok', 'gaji pokok', 'trim|required');

	$this->form_validation->set_rules('id_jabatan', 'id_jabatan', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tbl_gajipokok.php */
/* Location: ./application/controllers/Tbl_gajipokok.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-12-12 19:52:07 */
/* http://harviacode.com */