<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_karyawan_model extends CI_Model
{

    public $table = 'tbl_karyawan';
    public $id = 'id_karyawan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_karyawan,nomor_karyawan,nama_karyawan,jenis_kelamin,tanggal_lahir,alamat_karyawan,pendidikan_terakhir,divisi_karyawan');
        $this->datatables->from('tbl_karyawan');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_karyawan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('karyawan/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('karyawan/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('karyawan/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_karyawan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_karyawan', $q);
	$this->db->or_like('nomor_karyawan', $q);
	$this->db->or_like('nama_karyawan', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('alamat_karyawan', $q);
	$this->db->or_like('pendidikan_terakhir', $q);
	$this->db->or_like('divisi_karyawan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_karyawan', $q);
	$this->db->or_like('nomor_karyawan', $q);
	$this->db->or_like('nama_karyawan', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('alamat_karyawan', $q);
	$this->db->or_like('pendidikan_terakhir', $q);
	$this->db->or_like('divisi_karyawan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_karyawan_model.php */
/* Location: ./application/models/Tbl_karyawan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-12-12 19:52:07 */
/* http://harviacode.com */